# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

workflows:
  version: 2
  commit:
    jobs:
      - ruby-2.6
jobs:
  "ruby-2.6":
    docker:
      # specify the version you desire here
      - image: ruby:2.6
      - image: amazon/dynamodb-local

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4
            bundle exec appraisal install
      - run:
          name: run tests
          command: bundle exec appraisal rspec
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results